version: 2
updates:
    - package-ecosystem: "composer" # See documentation for possible values
      directory: "/buffet-api/" # Location of package manifests
      schedule:
          interval: "weekly"

    - package-ecosystem: "npm" # See documentation for possible values
      directory: "/buffet-app/" # Location of package manifests
      schedule:
          interval: "weekly"
