version: 2
updates:
    - package-ecosystem: "composer" # See documentation for possible values
      directory: "/buffet-api/" # Location of package manifests
      schedule:
          interval: "weekly"
      cooldown:
        default-days: 60
        semver-major-days: 60
        semver-minor-days: 30
        semver-patch-days: 14


    - package-ecosystem: "npm" # See documentation for possible values
      directory: "/buffet-app/" # Location of package manifests
      schedule:
          interval: "weekly"
      cooldown:
        default-days: 60
        semver-major-days: 60
        semver-minor-days: 30
        semver-patch-days: 14