stages:
    - test
    - Tests
    - Code Coverage

# Job to run PHPStan
phpstan:
    stage: Tests
    image: wlczak/buffet-test-prebuild:latest
    script:
        - cd buffet-api
        - composer install
        - ./vendor/bin/phpstan analyse --memory-limit 4G -c phpstan.neon --autoload-file vendor/autoload.php
          --error-format=gitlab src tests >> phpstan-result.json
    artifacts:
        reports:
            codequality: buffet-api/phpstan-result.json

# Job to run PHPUnit tests and generate the coverage output
phpunit:
    stage: Tests
    image: wlczak/buffet-test-prebuild:latest
    script:
        - echo ${ENV_CONFIG} >> conf/.env
        - cp -r conf/ buffet-api/
        - cd buffet-api
        - composer install
        - chown -R 1000:1000 conf/
        - ./vendor/bin/phpunit tests --testdox --colors=always --coverage-text --coverage-html tests/result
          --display-deprecations --display-phpunit-deprecations --fail-on-deprecation
          --fail-on-phpunit-deprecation
    artifacts:
        paths:
            - buffet-api/tests/result/
        expire_in: 1 hour

# Job to extract the coverage percentage from the PHPUnit output
phpunit-coverage:
    stage: Code Coverage
    image: wlczak/buffet-test-prebuild:latest
    script:
        - echo ${ENV_CONFIG} >> conf/.env
        - cp -r conf/ buffet-api/
        - cd buffet-api
        - composer install
        - chown -R 1000:1000 conf/
        - ./vendor/bin/phpunit tests --testdox --colors=never --coverage-text
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'

docker_build:
    stage: test
    image: docker:27.3.1
    variables:
        #DOCKER_HOST: "unix:///runner/services/docker/docker.sock"
        DOCKER_DRIVER: overlay2
    services:
        - name: docker:27.3.1-dind
          alias: docker
          command: ["--tls=false"]
    script:
        - docker version
        - cd scripts
        - sh docker_build_buffet.sh
        #   changed runner image
