stages:
    - PHP Unit Tests

phpunit:
    stage: PHP Unit Tests
    image: php:8.3-apache-bookworm
    before_script:
        - apt update && apt install git -y
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        - cd buffet-api
        - composer install
    script:
        - ./vendor/bin/phpunit tests --testdox --colors=always
