stages:
    - Tests
    - Code Coverage
    - Frontend Build Test
    - Docker Image Build

# Job to run PHPStan
phpstan:
    stage: Tests
    image: wlczak/buffet-test-prebuild:latest
    script:
        - cd buffet-api
        - composer install
        - ./vendor/bin/phpstan analyse --memory-limit 4G -c phpstan.neon --autoload-file vendor/autoload.php
          --error-format=gitlab src tests >> phpstan-result.json
    artifacts:
        reports:
            codequality: buffet-api/phpstan-result.json
    cache:
        key: composer
        paths:
        - buffet-api/vendor
        
# Job to run PHPUnit tests and generate the coverage output
phpunit:
    stage: Tests
    image: wlczak/buffet-test-prebuild:latest
    script:
        - cat ${ENV_CONFIG} >> conf/.env
        - cp -r conf/ buffet-api/
        - cd buffet-api
        - composer install
        - chown -R 1000:1000 conf/
        - rm -f test-db/database.sqlite
        - touch test-db/database.sqlite
        - sqlite3 test-db/database.sqlite < test-db/testing.db
        - ./vendor/bin/phpunit tests --testdox --colors=always --coverage-text --coverage-html tests/result
          --display-deprecations --display-phpunit-deprecations --fail-on-deprecation
          --fail-on-phpunit-deprecation
    artifacts:
        paths:
            - buffet-api/tests/result/
        expire_in: 7 days
    cache:
        key: composer
        paths:
        - buffet-api/vendor

# Job to extract the coverage percentage from the PHPUnit output
phpunit-coverage:
    stage: Code Coverage
    image: wlczak/buffet-test-prebuild:latest
    script:
        - cat ${ENV_CONFIG} >> conf/.env
        - cp -r conf/ buffet-api/
        - cd buffet-api
        - composer install
        - chown -R 1000:1000 conf/
        - rm -f test-db/database.sqlite
        - touch test-db/database.sqlite
        - sqlite3 test-db/database.sqlite < test-db/testing.db
        - ./vendor/bin/phpunit tests --testdox --colors=never --coverage-text
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    cache:
        key: composer
        paths:
        - buffet-api/vendor

frontend-build-test:
    stage: Frontend Build Test
    image: node:latest
    script:
        - cd buffet-app
        - npm install
        - npm run build
        - echo "cache should work now"
    cache:
        key: npm
        paths:
        - buffet-app/node_modules/

docker_build:
    stage: Docker Image Build
    image:
        name: wlczak/buffet-builder:latest
        pull_policy: always
    variables:
        DOCKER_DRIVER: overlay2
        #DOCKER_DIND: "docker:27.3.1-dind"
        #DOCKER_DIND: "docker:stable-dind"
        DOCKER_TLS_CERTDIR: ""
        #DOCKER_DIND: "docker:20.10.16-dind"
        #DOCKER_HOST: "tcp://docker:2375"
    services:
        - name: docker:27.3.1-dind
          alias: docker
          command: ["--tls=false"]
    script:
        - docker version
        - docker info
        #- docker load < /home/php-image.tar
        - date > buffet-api/build_date
        - cat buffet-api/build_date
        - cd scripts
        - npm --version
        - composer diagnose
        - sh docker_build_buffet.sh
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
