name: CI Pipeline

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"

permissions:
    contents: read

jobs:
    # steps:
    # - uses: actions/checkout@v4

    # - name: Validate composer.json and composer.lock
    #   run: composer validate --strict

    # - name: Cache Composer packages
    #   id: composer-cache
    #   uses: actions/cache@v3
    #   with:
    #     path: vendor
    #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-php-

    # - name: Install dependencies
    #   run: composer install --prefer-dist --no-progress

    phpstan:
        runs-on: ubuntu-latest
        container:
            image: wlczak/buffet-test-prebuild:latest
        steps:
            - uses: actions/checkout@v4

            - name: Validate composer.json and composer.lock
              run: |
                  cd buffet-api
                  composer validate --strict

            - name: Run PHPStan
              run: |
                  cd buffet-api
                  composer install
                  ./vendor/bin/phpstan analyse --memory-limit 4G -c phpstan.neon --autoload-file vendor/autoload.php --error-format=gitlab src tests >> phpstan-result.json
            # - name: Upload PHPStan report
            #   uses: actions/upload-artifact@v2
            #   with:
            #       name: phpstan-result.json
            #       path: buffet-api/phpstan-result.json

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
    write_config:
        runs-on: ubuntu-latest
        steps:
            - name: Write secret to file
              run: |
                 echo "${{ secrets.ENV_CONFIG }}" > config.txt
                 cat config.txt
    phpunit:
        runs-on: ubuntu-latest
        container:
            image: wlczak/buffet-test-prebuild:latest
        steps:
            - uses: actions/checkout@v4
              env:
                  ENV_CONFIG: ${{ secrets.ENV_CONFIG }}
            - name: Run PHPUnit Tests
              run: |
                  echo "${ENV_CONFIG}"
                  echo "${ENV_CONFIG}" >> conf/.env
                  cp -r conf/ buffet-api/
                  cd buffet-api
                  composer install
                  chown -R 1000:1000 conf/
                  rm -f test-db/database.sqlite
                  touch test-db/database.sqlite
                  sqlite3 test-db/database.sqlite < test-db/testing.db
                  ./vendor/bin/phpunit tests --testdox --colors=always --coverage-text --coverage-html tests/result --display-deprecations --display-phpunit-deprecations --fail-on-deprecation --fail-on-phpunit-deprecation
            - name: Upload PHPUnit Coverage HTML
              uses: actions/upload-artifact@v4
              with:
                  name: phpunit-coverage-html
                  path: buffet-api/tests/result/
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

    # phpunit-coverage:
    #   runs-on: ubuntu-latest
    #   container:
    #     image: wlczak/buffet-test-prebuild:latest
    #   steps:
    #     - uses: actions/checkout@v2
    #     - name: Run PHPUnit Coverage
    #       run: |
    #         cat ${ENV_CONFIG} >> conf/.env
    #         cp -r conf/ buffet-api/
    #         cd buffet-api
    #         composer install
    #         chown -R 1000:1000 conf/
    #         rm -f test-db/database.sqlite
    #         touch test-db/database.sqlite
    #         sqlite3 test-db/database.sqlite < test-db/testing.db
    #         ./vendor/bin/phpunit tests --testdox --colors=never --coverage-text
    #     - name: Cache composer dependencies
    #       uses: actions/cache@v2
    #       with:
    #         path: buffet-api/vendor
    #         key: composer-${{ hashFiles('**/composer.lock') }}

    # frontend-build-test:
    #   runs-on: ubuntu-latest
    #   container:
    #     image: node:latest
    #   steps:
    #     - uses: actions/checkout@v2
    #     - name: Build Frontend
    #       run: |
    #         cd buffet-app
    #         npm install
    #         npm run build
    #         echo "cache should work now"
    #     - name: Cache node modules
    #       uses: actions/cache@v2
    #       with:
    #         path: buffet-app/node_modules
    #         key: npm-${{ hashFiles('**/package-lock.json') }}

    # docker_build:
    #   if: github.ref == 'refs/heads/main'
    #   runs-on: ubuntu-latest
    #   container:
    #     image: wlczak/buffet-builder:latest
    #     options: --pull always
    #   env:
    #     DOCKER_DRIVER: overlay2
    #     DOCKER_TLS_CERTDIR: ""
    #   services:
    #     docker:
    #       image: docker:27.3.1-dind
    #       options: --tls=false
    #   steps:
    #     - uses: actions/checkout@v2
    #     - name: Check Docker version and info
    #       run: |
    #         docker version
    #         docker info
    #     - name: Create build date
    #       run: |
    #         date > buffet-api/build_date
    #         cat buffet-api/build_date
    #     - name: Execute Docker build script
    #       run: |
    #         cd scripts
    #         npm --version
    #         composer diagnose
    #         sh docker_build_buffet.sh
    #     - name: Cache Docker data
    #       uses: actions/cache@v2
    #       with:
    #         path: /var/lib/docker
    #         key: docker
    #     - name: Cache node modules
    #       uses: actions/cache@v2
    #       with:
    #         path: buffet-app/node_modules
    #         key: npm-${{ hashFiles('**/package-lock.json') }}
    #     - name: Cache composer dependencies
    #       uses: actions/cache@v2
    #       with:
    #         path: buffet-api/vendor
    #         key: composer-${{ hashFiles('**/composer.lock') }}
